const PRODUCTS = [
  {
    id: "el-guayabal",
    name: "El Guayabal",
    price: "$400",
    priceValue: 400,
    priceId: "price_el_guayabal_250g",
    image: "images/el-guayabal.png",
    images: ["images/el-guayabal.png"],
    badge: "Gesha",
    summary:
      "Gesha floral y cítrico con jazmín, té de limón y durazno, marcado por el terruño de Ixhuatlán del Café.",
    description:
      "En este lote se juntan 2 factores que hacen a este lote un muy buen gesha: su genética y su terruño. Genética: Al ser un buen gesha es fácil percibir notas florales como jazmín y té de limón, así como su característica nota de durazno. Terruño: Ixhuatlán del café es muy famoso por producir cafés con sabor a toronja y lima. Estos descriptores fueron mencionados por Carlos Juárez en la competencia mexicana de baristas región sur – sureste y al ser muy claros le dieron la victoria.",
    tastingNotes: ["Jazmín", "Té de limón", "Durazno", "Toronja", "Lima"],
    origin: "Ixhuatlán del Café, Veracruz",
    notes: "87.13 pts · Lavado",
    weight: "250 gr.",
    presentation: "250 gr.",
    cupScore: "87.13",
    process: "Lavado",
    fermentation: "Aerobia 24H promedio",
    drying: "En guardiola 48 horas",
    producer: "Jesús Sabag",
    variety: "Gesha",
    locality: "Ixhuatlán del Café",
    farm: "El Guayabal",
    altitude: "1450 msnm",
    roastOptions: ["Brew Bar", "Espresso"],
    grindOptions: ["Grano", "Fino", "Medio", "Grueso"],
    category: "Varios",
    sizes: [
      {
        label: "250 gr.",
        grams: 250,
        price: 400,
        priceId: "price_el_guayabal_250g",
      },
    ],
  },
  {
    id: "catuai-amarillo",
    name: "Catuaí Amarillo",
    price: "$580",
    priceValue: 580,
    priceId: "price_catuai_amarillo_500g",
    image: "images/catuai-amarillo.png",
    images: ["images/catuai-amarillo.png"],
    badge: "Orgánico",
    summary:
      "Lote orgánico de cooperativa con perfil cítrico, dulce y herbal, pensado para clientes que valoran el origen y el impacto ambiental.",
    description:
      "Este café es producido por una cooperativa conformada por 16 productores los cuales están asociados en este proyecto, produciendo café orgánico certificado y destinado para la exportación a Estados Unidos y Europa.\n\nSu proceso es muy simple, consiste en un desmucilaginado ecológico secado en guardiola, en donde simplemente destacan la nutrición de sus suelos, así como la alta calidad del café producido en el municipio de Chocamán, Veracruz.\n\nSu perfil es cítrico, dulce, con notas a toronja, lima, miel y manzanilla. Principalmente procuramos vender este café como un lote de café orgánico para aquellos clientes quienes el impacto ambiental es un factor determinante en la adquisición de sus productos de consumo.",
    tastingNotes: ["Toronja", "Lima", "Miel", "Manzanilla"],
    origin: "Chocamán, Veracruz",
    notes: "84.96 pts · Desmucilaginado",
    weight: "500 gr.",
    presentation: "500 gr.",
    cupScore: "84.96",
    process: "Desmucilaginado",
    fermentation: "Sin fermentación",
    drying: "En guardiola",
    producer: "16 Productores Asociados",
    variety: "Typica, Bourbon, Garnica y Marsellesa",
    locality: "Chocamán",
    farm: "16 fincas de diferentes productores",
    altitude: "1250–1450 msnm",
    roastOptions: ["Brew Bar", "Espresso"],
    grindOptions: ["Grano", "Medio", "Fino"],
    category: "Varios",
    sizes: [
      {
        label: "500 gr.",
        grams: 500,
        price: 580,
        priceId: "price_catuai_amarillo_500g",
      },
    ],
  },
  {
    id: "corahe",
    name: "Corahe",
    price: "$520",
    priceValue: 520,
    priceId: "price_corahe_500g",
    image: "images/corahe.png",
    images: ["images/corahe.png"],
    badge: "Experimental",
    summary:
      "Proceso Natural + Honey intensamente vinoso, con frutas rojas, vino tinto y cacao fermentado.",
    description:
      "Este es un café para los amantes del perfil vinoso, una mezcla de variedades que al fermentarse 10 días en tanques de plástico producen una gran cantidad de alcoholes y ácidos, creando un intenso aroma a frutas rojas/tropicales, vino tinto y cacao fermentado.\n\nDespués de la fermentación el café es secado en guardiolas durante 40 horas en donde por el movimiento de las cerezas se despulpa la mitad del café que se está secando.\n\nAl salir de la secadora encontramos 2 procesos juntos, las cerezas que se despulparon por el movimiento de la guardiola dieron paso a un café honey, mientras que aquellas que no se despulparon fueron secadas como un proceso natural, creando así un proceso llamado NATURAL/HONEY.\n\nSegún su productor Marco Córdoba esta técnica le permite procesar un café muy exótico y complejo mientras ahorra agua.",
    tastingNotes: ["Frutas rojas", "Fruta tropical", "Vino tinto", "Cacao fermentado"],
    origin: "Totutla, Santa Rita, Veracruz",
    notes: "84.22 pts · Natural + Honey",
    weight: "500 gr.",
    presentation: "500 gr.",
    cupScore: "84.22",
    process: "Natural + Honey",
    fermentation: "Anaerobia de 10 días",
    drying: "En guardiolas 40 horas",
    producer: "Rigoberto Córdoba",
    variety: "CR95, Caturra y Garnica",
    locality: "Totutla, Santa Rita",
    altitude: "1210 msnm",
    roastOptions: ["Brew Bar", "Espresso"],
    grindOptions: ["Grano", "Fino", "Medio", "Grueso"],
    category: "Varios",
    sizes: [
      {
        label: "500 gr.",
        grams: 500,
        price: 520,
        priceId: "price_corahe_500g",
      },
    ],
  },
  {
    id: "cosautlan",
    name: "Cosautlán",
    price: "$442",
    priceValue: 442,
    priceId: "price_cosautlan_500g",
    originalPrice: "$520",
    image: "images/cosautlan.png",
    images: ["images/cosautlan.png"],
    badge: "Oferta",
    summary:
      "Natural de secado lento en camas africanas con moras, arándanos, chocolate, caramelo y avellana.",
    description:
      "Ubicado en el municipio de Cosautlán de Carvajal, se encuentra este café producido por Carlos Cadena.\n\nEs el resultado de un proceso natural que realza sus notas frutales y fermentadas, recordando a un vino tinto.\n\nEl secado en camas africanas permite un proceso lento y controlado, lo que contribuye a su complejidad.\n\nAl paladar se revelan notas de moras y arándanos, chocolate, caramelo y avellana. Sin duda, un café complejo e inigualable.",
    tastingNotes: ["Moras", "Arándanos", "Chocolate", "Caramelo", "Avellana"],
    origin: "Cosautlán de Carvajal, Veracruz",
    notes: "85 pts · Natural",
    weight: "500 gr.",
    presentation: "500 gr.",
    cupScore: "85",
    process: "Natural",
    fermentation: "Oxidación",
    drying: "Secado en camas africanas",
    producer: "Carlos Cadena",
    variety: "Gesha, Típica, Mundo Maya, Sarchimor y Marsellesa",
    locality: "Cosautlán de Carvajal",
    altitude: "1350 msnm",
    roastOptions: ["Brew Bar", "Espresso"],
    grindOptions: ["Grano", "Fino", "Medio", "Grueso"],
    category: "Varios",
    sizes: [
      {
        label: "500 gr.",
        grams: 500,
        price: 442,
        priceId: "price_cosautlan_500g",
      },
    ],
  },
  {
    id: "zongolica",
    name: "Zongolica",
    price: "$450",
    priceValue: 450,
    priceId: "price_zongolica_500g",
    image: "images/zongolica.png",
    images: ["images/zongolica.png"],
    badge: "Sierra",
    summary:
      "Perfil clásico de la sierra de Zongolica: cítrico, dulce y de cuerpo ligero.",
    description:
      "Zongolica es un terruño muy privilegiado por su clima frío, su alta precipitación y el suelo rocoso que lo caracteriza.\n\nEn Impetus comercializamos distintos cafés de la sierra de Zongolica y este lote expresa el perfil clásico de la región con notas cítricas, dulces y un cuerpo ligero.",
    tastingNotes: ["Cítricos", "Dulzor limpio", "Cuerpo ligero"],
    origin: "Zongolica, Veracruz",
    notes: "82.5 pts · Lavado",
    weight: "500 gr.",
    presentation: "500 gr.",
    cupScore: "82.5",
    process: "Lavado",
    fermentation: "Oxidación 40 hrs",
    producer: "Varios",
    variety: "CR95, Sarchimor y Obatá",
    locality: "Zongolica",
    farm: "Vista Hermosa",
    altitude: "1200–1300 msnm",
    roastOptions: ["Brew Bar", "Espresso"],
    grindOptions: ["Grano", "Fino", "Medio", "Grueso"],
    category: "Varios",
    sizes: [
      {
        label: "500 gr.",
        grams: 500,
        price: 450,
        priceId: "price_zongolica_500g",
      },
    ],
  },
];

if (typeof window !== "undefined") {
  window.PRODUCTS = PRODUCTS;
}
