const PRODUCTS = [
  {
    id: "catuai-amarillo",
    name: "Catuaí Amarillo",
    price: "Desde $199",
    image: "images/node-21.png",
    images: [
      "images/node-21.png",
      "images/node-21.png",
      "images/node-21.png",
      "images/node-21.png",
      "images/node-21.png",
    ],
    description: "Un café brillante y balanceado, con notas cítricas suaves y un cuerpo sedoso.",
    origin: "Veracruz",
    notes: "Tostado medio",
    weight: "500g",
    badge: "Nuevo",
    features: [
      "Notas cítricas suaves",
      "Cuerpo sedoso",
      "Tostado medio",
      "Presentación de 500g",
    ],
  },
  {
    id: "zongolica",
    name: "Zongolica",
    price: "Desde $299",
    image: "images/node-30.png",
    images: [
      "images/node-30.png",
      "images/node-30.png",
      "images/node-30.png",
      "images/node-30.png",
      "images/node-30.png",
    ],
    description: "Perfil dulce con notas a cacao y un final limpio, ideal para métodos filtrados.",
    origin: "Veracruz",
    notes: "Tostado medio",
    weight: "500g",
    badge: "Nuevo",
    features: [
      "Notas a cacao",
      "Final limpio",
      "Tostado medio",
      "Presentación de 500g",
    ],
  },
  {
    id: "cosautlan",
    name: "Cosautlán",
    price: "Desde $299",
    image: "images/node-38.png",
    images: [
      "images/node-38.png",
      "images/node-38.png",
      "images/node-38.png",
      "images/node-38.png",
      "images/node-38.png",
    ],
    description: "Sabor redondo con notas avellanadas y un aroma profundo que perdura.",
    origin: "Veracruz",
    notes: "Tostado medio",
    weight: "500g",
    badge: "Nuevo",
    features: [
      "Notas avellanadas",
      "Aroma profundo",
      "Tostado medio",
      "Presentación de 500g",
    ],
  },
];
